MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: ResNet.ResNet50_conv4_body
  FASTER_RCNN: True
NUM_GPUS: 4
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 70000
  STEPS: [0, 50000]
RPN:
  SIZES: (16, 32, 64, 128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: ResNet.ResNet_roi_conv5_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  SCALES: (500,)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 64
  JOINT_TRAINING: True
  GT_SCORES: True
  DISTILL_LAMBDA: 1.0
  DISTILL_TEMPERATURE: 1.0
  TRACKER_SCORE: 1.0
TEST:
  SCALE: 500
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 1000
